-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/CQM5PxN3SbJqEd3
vl1S5I3i/gVkLrdGjSKtjneciWegCgYIKoZIzj0DAQehRANCAARygNoeqR/bwMS8
AchJfcDnre3Z0TxumK5HJ3W5nxYzltDzqOdPFsCzIx87GlWKUB1tVQPXi8TpOZp0
ZLn/lXgh
-----END PRIVATE KEY-----